<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Portfolio Analytics | Financial Analytics</title>
  <meta name="description" content="This is a practice manual using R for financial analytics." />
  <meta name="generator" content="bookdown 0.13 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Portfolio Analytics | Financial Analytics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a practice manual using R for financial analytics." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Portfolio Analytics | Financial Analytics" />
  
  <meta name="twitter:description" content="This is a practice manual using R for financial analytics." />
  

<meta name="author" content="Bill Foote" />


<meta name="date" content="2019-12-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="market-risk.html"/>
<link rel="next" href="aggregating-enterprise-risk.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preliminaries</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#the-basic-problem"><i class="fa fa-check"></i><b>1.1</b> The basic problem</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#analytics"><i class="fa fa-check"></i><b>1.2</b> Analytics</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#why-this-book"><i class="fa fa-check"></i><b>1.3</b> Why this book?</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#a-useful-way-to-start-private-placement-finance"><i class="fa fa-check"></i><b>1.4</b> A useful way to start: private placement finance</a><ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#the-market-for-private-placement"><i class="fa fa-check"></i><b>1.4.1</b> The market for private placement</a></li>
<li class="chapter" data-level="1.4.2" data-path="index.html"><a href="index.html#a-deal-emerges-from-the-mist"><i class="fa fa-check"></i><b>1.4.2</b> A deal emerges from the mist</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#chapter-outline"><i class="fa fa-check"></i><b>1.5</b> Chapter Outline</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html"><i class="fa fa-check"></i><b>2</b> R Warm-ups in Finance</a><ul>
<li class="chapter" data-level="2.1" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#imagine-this"><i class="fa fa-check"></i><b>2.1</b> Imagine This</a><ul>
<li class="chapter" data-level="2.1.1" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#modeling-process"><i class="fa fa-check"></i><b>2.1.1</b> Modeling process</a></li>
<li class="chapter" data-level="2.1.2" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#chapter-overview"><i class="fa fa-check"></i><b>2.1.2</b> Chapter overview</a></li>
<li class="chapter" data-level="2.1.3" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#what-is-r"><i class="fa fa-check"></i><b>2.1.3</b> What is <code>R</code>?</a></li>
<li class="chapter" data-level="2.1.4" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#r-for-analytics"><i class="fa fa-check"></i><b>2.1.4</b> <code>R</code> for analytics</a></li>
<li class="chapter" data-level="2.1.5" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#hot-and-cold-running-resources"><i class="fa fa-check"></i><b>2.1.5</b> Hot and cold running resources</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#tickling-the-ivories"><i class="fa fa-check"></i><b>2.2</b> Tickling the Ivories</a><ul>
<li class="chapter" data-level="2.2.1" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#try-this-exercise"><i class="fa fa-check"></i><b>2.2.1</b> Try this exercise</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#building-some-character"><i class="fa fa-check"></i><b>2.3</b> Building Some Character</a><ul>
<li class="chapter" data-level="2.3.1" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#the-plot-thickens"><i class="fa fa-check"></i><b>2.3.1</b> The plot thickens</a></li>
<li class="chapter" data-level="2.3.2" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#try-this-example"><i class="fa fa-check"></i><b>2.3.2</b> Try this example</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#arrays-and-you"><i class="fa fa-check"></i><b>2.4</b> Arrays and You</a><ul>
<li class="chapter" data-level="2.4.1" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#try-this-exercise-1"><i class="fa fa-check"></i><b>2.4.1</b> Try this exercise</a></li>
<li class="chapter" data-level="2.4.2" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#more-about-residuals"><i class="fa fa-check"></i><b>2.4.2</b> More about residuals</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#more-array-work"><i class="fa fa-check"></i><b>2.5</b> More Array Work</a></li>
<li class="chapter" data-level="2.6" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#summary"><i class="fa fa-check"></i><b>2.6</b> Summary</a></li>
<li class="chapter" data-level="2.7" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#further-reading"><i class="fa fa-check"></i><b>2.7</b> Further Reading</a></li>
<li class="chapter" data-level="2.8" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#practice-set"><i class="fa fa-check"></i><b>2.8</b> Practice Set</a><ul>
<li class="chapter" data-level="2.8.1" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#purpose-process-product"><i class="fa fa-check"></i><b>2.8.1</b> Purpose, Process, Product</a></li>
<li class="chapter" data-level="2.8.2" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#r-markdown-set-up"><i class="fa fa-check"></i><b>2.8.2</b> <code>R Markdown</code> set up</a></li>
<li class="chapter" data-level="2.8.3" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#exercise-1-a-financial-planning-problem"><i class="fa fa-check"></i><b>2.8.3</b> Exercise 1: a financial planning problem</a></li>
<li class="chapter" data-level="2.8.4" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#exercise-2-risk-driver-model-using-regression-analysis"><i class="fa fa-check"></i><b>2.8.4</b> Exercise 2: risk driver model using regression analysis</a></li>
<li class="chapter" data-level="2.8.5" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#exercise-3-commercial-loan-projection-using-regression"><i class="fa fa-check"></i><b>2.8.5</b> Exercise 3: commercial loan projection using regression</a></li>
<li class="chapter" data-level="2.8.6" data-path="r-warm-ups-in-finance.html"><a href="r-warm-ups-in-finance.html#work-flow"><i class="fa fa-check"></i><b>2.8.6</b> Work Flow</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="r-data-modeling.html"><a href="r-data-modeling.html"><i class="fa fa-check"></i><b>3</b> R Data Modeling</a><ul>
<li class="chapter" data-level="3.1" data-path="r-data-modeling.html"><a href="r-data-modeling.html#imagine-this-1"><i class="fa fa-check"></i><b>3.1</b> Imagine This</a></li>
<li class="chapter" data-level="3.2" data-path="r-data-modeling.html"><a href="r-data-modeling.html#pivot-tables-and-vertical-lookups"><i class="fa fa-check"></i><b>3.2</b> Pivot tables and Vertical Lookups</a><ul>
<li class="chapter" data-level="3.2.1" data-path="r-data-modeling.html"><a href="r-data-modeling.html#some-definitions"><i class="fa fa-check"></i><b>3.2.1</b> Some definitions</a></li>
<li class="chapter" data-level="3.2.2" data-path="r-data-modeling.html"><a href="r-data-modeling.html#pivot-and-parry"><i class="fa fa-check"></i><b>3.2.2</b> Pivot and Parry</a></li>
<li class="chapter" data-level="3.2.3" data-path="r-data-modeling.html"><a href="r-data-modeling.html#try-this-exercise-2"><i class="fa fa-check"></i><b>3.2.3</b> Try this exercise</a></li>
<li class="chapter" data-level="3.2.4" data-path="r-data-modeling.html"><a href="r-data-modeling.html#now-to-vlookup"><i class="fa fa-check"></i><b>3.2.4</b> Now to VLOOKUP</a></li>
<li class="chapter" data-level="3.2.5" data-path="r-data-modeling.html"><a href="r-data-modeling.html#try-this-exercise-3"><i class="fa fa-check"></i><b>3.2.5</b> Try this exercise</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="r-data-modeling.html"><a href="r-data-modeling.html#why-functions"><i class="fa fa-check"></i><b>3.3</b> Why Functions?</a><ul>
<li class="chapter" data-level="3.3.1" data-path="r-data-modeling.html"><a href="r-data-modeling.html#what-should-be-a-function"><i class="fa fa-check"></i><b>3.3.1</b> What should be a function?</a></li>
<li class="chapter" data-level="3.3.2" data-path="r-data-modeling.html"><a href="r-data-modeling.html#shooting-trouble"><i class="fa fa-check"></i><b>3.3.2</b> Shooting trouble</a></li>
<li class="chapter" data-level="3.3.3" data-path="r-data-modeling.html"><a href="r-data-modeling.html#what-the-function-can-see-and-do"><i class="fa fa-check"></i><b>3.3.3</b> What the function can see and do</a></li>
<li class="chapter" data-level="3.3.4" data-path="r-data-modeling.html"><a href="r-data-modeling.html#try-this"><i class="fa fa-check"></i><b>3.3.4</b> Try this …</a></li>
<li class="chapter" data-level="3.3.5" data-path="r-data-modeling.html"><a href="r-data-modeling.html#mind-the-interface"><i class="fa fa-check"></i><b>3.3.5</b> Mind the Interface!</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="r-data-modeling.html"><a href="r-data-modeling.html#making-distributions"><i class="fa fa-check"></i><b>3.4</b> Making distributions</a><ul>
<li class="chapter" data-level="3.4.1" data-path="r-data-modeling.html"><a href="r-data-modeling.html#try-this-exercise-4"><i class="fa fa-check"></i><b>3.4.1</b> Try this exercise</a></li>
<li class="chapter" data-level="3.4.2" data-path="r-data-modeling.html"><a href="r-data-modeling.html#picture-this"><i class="fa fa-check"></i><b>3.4.2</b> Picture this</a></li>
<li class="chapter" data-level="3.4.3" data-path="r-data-modeling.html"><a href="r-data-modeling.html#try-another-exercise"><i class="fa fa-check"></i><b>3.4.3</b> Try another exercise</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="r-data-modeling.html"><a href="r-data-modeling.html#optimization"><i class="fa fa-check"></i><b>3.5</b> Optimization</a><ul>
<li class="chapter" data-level="3.5.1" data-path="r-data-modeling.html"><a href="r-data-modeling.html#try-this-exercise-5"><i class="fa fa-check"></i><b>3.5.1</b> Try this exercise</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="r-data-modeling.html"><a href="r-data-modeling.html#estimate-until-morale-improves"><i class="fa fa-check"></i><b>3.6</b> Estimate until morale improves…</a><ul>
<li class="chapter" data-level="3.6.1" data-path="r-data-modeling.html"><a href="r-data-modeling.html#try-this-exercise-6"><i class="fa fa-check"></i><b>3.6.1</b> Try this exercise</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="r-data-modeling.html"><a href="r-data-modeling.html#summary-1"><i class="fa fa-check"></i><b>3.7</b> Summary</a></li>
<li class="chapter" data-level="3.8" data-path="r-data-modeling.html"><a href="r-data-modeling.html#further-reading-1"><i class="fa fa-check"></i><b>3.8</b> Further Reading</a></li>
<li class="chapter" data-level="3.9" data-path="r-data-modeling.html"><a href="r-data-modeling.html#practice-sets"><i class="fa fa-check"></i><b>3.9</b> Practice Sets</a><ul>
<li class="chapter" data-level="3.9.1" data-path="r-data-modeling.html"><a href="r-data-modeling.html#set-a"><i class="fa fa-check"></i><b>3.9.1</b> Set A</a></li>
<li class="chapter" data-level="3.9.2" data-path="r-data-modeling.html"><a href="r-data-modeling.html#set-b"><i class="fa fa-check"></i><b>3.9.2</b> Set B</a></li>
<li class="chapter" data-level="3.9.3" data-path="r-data-modeling.html"><a href="r-data-modeling.html#practice-set-debrief"><i class="fa fa-check"></i><b>3.9.3</b> Practice Set Debrief</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="r-data-modeling.html"><a href="r-data-modeling.html#project"><i class="fa fa-check"></i><b>3.10</b> Project</a><ul>
<li class="chapter" data-level="3.10.1" data-path="r-data-modeling.html"><a href="r-data-modeling.html#background"><i class="fa fa-check"></i><b>3.10.1</b> Background</a></li>
<li class="chapter" data-level="3.10.2" data-path="r-data-modeling.html"><a href="r-data-modeling.html#data"><i class="fa fa-check"></i><b>3.10.2</b> Data</a></li>
<li class="chapter" data-level="3.10.3" data-path="r-data-modeling.html"><a href="r-data-modeling.html#workflow"><i class="fa fa-check"></i><b>3.10.3</b> Workflow</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="r-data-modeling.html"><a href="r-data-modeling.html#references"><i class="fa fa-check"></i><b>3.11</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html"><i class="fa fa-check"></i><b>4</b> Macrofinancial Data Analysis</a><ul>
<li class="chapter" data-level="4.1" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html#imagine-this-2"><i class="fa fa-check"></i><b>4.1</b> Imagine This</a><ul>
<li class="chapter" data-level="4.1.1" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html#working-an-example"><i class="fa fa-check"></i><b>4.1.1</b> Working an example</a></li>
<li class="chapter" data-level="4.1.2" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html#how-we-will-proceed"><i class="fa fa-check"></i><b>4.1.2</b> How we will proceed</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html#building-the-stylized-facts"><i class="fa fa-check"></i><b>4.2</b> Building the Stylized Facts</a><ul>
<li class="chapter" data-level="4.2.1" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html#implications"><i class="fa fa-check"></i><b>4.2.1</b> Implications</a></li>
<li class="chapter" data-level="4.2.2" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html#now-for-somthing-really-interestingagain"><i class="fa fa-check"></i><b>4.2.2</b> Now for somthing really interesting…again</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html#getting-caught-in-the-cross-current"><i class="fa fa-check"></i><b>4.3</b> Getting Caught in the Cross-Current</a><ul>
<li class="chapter" data-level="4.3.1" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html#on-to-quantiles"><i class="fa fa-check"></i><b>4.3.1</b> On to quantiles</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html#time-is-on-our-side"><i class="fa fa-check"></i><b>4.4</b> Time is on our Side</a><ul>
<li class="chapter" data-level="4.4.1" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html#forecasting-gnp"><i class="fa fa-check"></i><b>4.4.1</b> Forecasting GNP</a></li>
<li class="chapter" data-level="4.4.2" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html#residuals-again"><i class="fa fa-check"></i><b>4.4.2</b> Residuals again</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html#give-it-the-boot"><i class="fa fa-check"></i><b>4.5</b> Give it the Boot</a><ul>
<li class="chapter" data-level="4.5.1" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html#exercises"><i class="fa fa-check"></i><b>4.5.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html#summary-2"><i class="fa fa-check"></i><b>4.6</b> Summary</a></li>
<li class="chapter" data-level="4.7" data-path="macrofinancial-data-analysis.html"><a href="macrofinancial-data-analysis.html#further-reading-2"><i class="fa fa-check"></i><b>4.7</b> Further Reading</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="market-risk.html"><a href="market-risk.html"><i class="fa fa-check"></i><b>5</b> Market Risk</a><ul>
<li class="chapter" data-level="5.1" data-path="market-risk.html"><a href="market-risk.html#imagine-this-3"><i class="fa fa-check"></i><b>5.1</b> Imagine This</a></li>
<li class="chapter" data-level="5.2" data-path="market-risk.html"><a href="market-risk.html#what-is-market-risk"><i class="fa fa-check"></i><b>5.2</b> What is Market Risk?</a><ul>
<li class="chapter" data-level="5.2.1" data-path="market-risk.html"><a href="market-risk.html#try-this-exercise-7"><i class="fa fa-check"></i><b>5.2.1</b> Try this exercise</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="market-risk.html"><a href="market-risk.html#history-speaks"><i class="fa fa-check"></i><b>5.3</b> History Speaks</a></li>
<li class="chapter" data-level="5.4" data-path="market-risk.html"><a href="market-risk.html#now-to-the-matter-at-hand"><i class="fa fa-check"></i><b>5.4</b> Now to the Matter at Hand</a><ul>
<li class="chapter" data-level="5.4.1" data-path="market-risk.html"><a href="market-risk.html#try-this-example-1"><i class="fa fa-check"></i><b>5.4.1</b> Try this example</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="market-risk.html"><a href="market-risk.html#carl-friedrich-gauss-i-presume"><i class="fa fa-check"></i><b>5.5</b> Carl Friedrich Gauss, I Presume…</a><ul>
<li class="chapter" data-level="5.5.1" data-path="market-risk.html"><a href="market-risk.html#try-this-example-2"><i class="fa fa-check"></i><b>5.5.1</b> Try this example</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="market-risk.html"><a href="market-risk.html#back-to-the-future"><i class="fa fa-check"></i><b>5.6</b> Back to the Future</a></li>
<li class="chapter" data-level="5.7" data-path="market-risk.html"><a href="market-risk.html#try-this-example-3"><i class="fa fa-check"></i><b>5.7</b> Try this example</a></li>
<li class="chapter" data-level="5.8" data-path="market-risk.html"><a href="market-risk.html#lets-go-to-extremes"><i class="fa fa-check"></i><b>5.8</b> Let’s Go to Extremes</a><ul>
<li class="chapter" data-level="5.8.1" data-path="market-risk.html"><a href="market-risk.html#try-this-example-4"><i class="fa fa-check"></i><b>5.8.1</b> Try this example</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="market-risk.html"><a href="market-risk.html#all-together-now"><i class="fa fa-check"></i><b>5.9</b> All Together Now</a></li>
<li class="chapter" data-level="5.10" data-path="market-risk.html"><a href="market-risk.html#summary-3"><i class="fa fa-check"></i><b>5.10</b> Summary</a></li>
<li class="chapter" data-level="5.11" data-path="market-risk.html"><a href="market-risk.html#further-reading-3"><i class="fa fa-check"></i><b>5.11</b> Further Reading</a></li>
<li class="chapter" data-level="5.12" data-path="market-risk.html"><a href="market-risk.html#practice-laboratory"><i class="fa fa-check"></i><b>5.12</b> Practice Laboratory</a><ul>
<li class="chapter" data-level="5.12.1" data-path="market-risk.html"><a href="market-risk.html#practice-laboratory-1"><i class="fa fa-check"></i><b>5.12.1</b> Practice laboratory #1</a></li>
<li class="chapter" data-level="5.12.2" data-path="market-risk.html"><a href="market-risk.html#practice-laboratory-2"><i class="fa fa-check"></i><b>5.12.2</b> Practice laboratory #2</a></li>
</ul></li>
<li class="chapter" data-level="5.13" data-path="market-risk.html"><a href="market-risk.html#project-1"><i class="fa fa-check"></i><b>5.13</b> Project</a><ul>
<li class="chapter" data-level="5.13.1" data-path="market-risk.html"><a href="market-risk.html#background-1"><i class="fa fa-check"></i><b>5.13.1</b> Background</a></li>
<li class="chapter" data-level="5.13.2" data-path="market-risk.html"><a href="market-risk.html#data-1"><i class="fa fa-check"></i><b>5.13.2</b> Data</a></li>
<li class="chapter" data-level="5.13.3" data-path="market-risk.html"><a href="market-risk.html#workflow-1"><i class="fa fa-check"></i><b>5.13.3</b> Workflow</a></li>
<li class="chapter" data-level="5.13.4" data-path="market-risk.html"><a href="market-risk.html#assessment"><i class="fa fa-check"></i><b>5.13.4</b> Assessment</a></li>
</ul></li>
<li class="chapter" data-level="5.14" data-path="market-risk.html"><a href="market-risk.html#references-1"><i class="fa fa-check"></i><b>5.14</b> References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html"><i class="fa fa-check"></i><b>6</b> Portfolio Analytics</a><ul>
<li class="chapter" data-level="6.1" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#imagine-this-4"><i class="fa fa-check"></i><b>6.1</b> Imagine This</a><ul>
<li class="chapter" data-level="6.1.1" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#our-working-example"><i class="fa fa-check"></i><b>6.1.1</b> Our “working example”</a></li>
<li class="chapter" data-level="6.1.2" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#this-chapter"><i class="fa fa-check"></i><b>6.1.2</b> This chapter</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#lets-walk-before-we-run"><i class="fa fa-check"></i><b>6.2</b> Let’s Walk Before We Run</a></li>
<li class="chapter" data-level="6.3" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#all-in"><i class="fa fa-check"></i><b>6.3</b> All In</a><ul>
<li class="chapter" data-level="6.3.1" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#try-this-exercise-8"><i class="fa fa-check"></i><b>6.3.1</b> Try this exercise</a></li>
<li class="chapter" data-level="6.3.2" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#lets-keep-moving-on"><i class="fa fa-check"></i><b>6.3.2</b> Let’s keep moving on…</a></li>
<li class="chapter" data-level="6.3.3" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#try-this-exercise-9"><i class="fa fa-check"></i><b>6.3.3</b> Try this exercise</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#optimizing-a-portfolio"><i class="fa fa-check"></i><b>6.4</b> Optimizing a Portfolio</a><ul>
<li class="chapter" data-level="6.4.1" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#try-this-exercise-10"><i class="fa fa-check"></i><b>6.4.1</b> Try this exercise</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#summary-4"><i class="fa fa-check"></i><b>6.5</b> Summary</a></li>
<li class="chapter" data-level="6.6" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#further-reading-4"><i class="fa fa-check"></i><b>6.6</b> Further Reading</a></li>
<li class="chapter" data-level="6.7" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#practice-laboratory-3"><i class="fa fa-check"></i><b>6.7</b> Practice Laboratory</a><ul>
<li class="chapter" data-level="6.7.1" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#practice-laboratory-1-1"><i class="fa fa-check"></i><b>6.7.1</b> Practice laboratory #1</a></li>
<li class="chapter" data-level="6.7.2" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#practice-laboratory-2-1"><i class="fa fa-check"></i><b>6.7.2</b> Practice laboratory #2</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#project-2"><i class="fa fa-check"></i><b>6.8</b> Project</a><ul>
<li class="chapter" data-level="6.8.1" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#background-2"><i class="fa fa-check"></i><b>6.8.1</b> Background</a></li>
<li class="chapter" data-level="6.8.2" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#data-2"><i class="fa fa-check"></i><b>6.8.2</b> Data</a></li>
<li class="chapter" data-level="6.8.3" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#workflow-2"><i class="fa fa-check"></i><b>6.8.3</b> Workflow</a></li>
<li class="chapter" data-level="6.8.4" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#assessment-1"><i class="fa fa-check"></i><b>6.8.4</b> Assessment</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="portfolio-analytics.html"><a href="portfolio-analytics.html#references-2"><i class="fa fa-check"></i><b>6.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html"><i class="fa fa-check"></i><b>7</b> Aggregating Enterprise Risk</a><ul>
<li class="chapter" data-level="7.1" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#the-problem-with-enterprise-risk"><i class="fa fa-check"></i><b>7.1</b> The Problem with Enterprise Risk</a></li>
<li class="chapter" data-level="7.2" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#lets-make-copulas"><i class="fa fa-check"></i><b>7.2</b> Let’s make copulas</a><ul>
<li class="chapter" data-level="7.2.1" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#we-do-this-from-scratch."><i class="fa fa-check"></i><b>7.2.1</b> We do this from scratch.</a></li>
<li class="chapter" data-level="7.2.2" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#example"><i class="fa fa-check"></i><b>7.2.2</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#sklars-in-the-house"><i class="fa fa-check"></i><b>7.3</b> Sklar’s in the house…</a></li>
<li class="chapter" data-level="7.4" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#analyze-that"><i class="fa fa-check"></i><b>7.4</b> Analyze that…</a><ul>
<li class="chapter" data-level="7.4.1" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#example-1"><i class="fa fa-check"></i><b>7.4.1</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#risk-measures"><i class="fa fa-check"></i><b>7.5</b> Risk measures</a><ul>
<li class="chapter" data-level="7.5.1" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#example-2"><i class="fa fa-check"></i><b>7.5.1</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#lets-build-an-app"><i class="fa fa-check"></i><b>7.6</b> Let’s build an app …</a><ul>
<li class="chapter" data-level="7.6.1" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#analytics-1"><i class="fa fa-check"></i><b>7.6.1</b> Analytics</a></li>
<li class="chapter" data-level="7.6.2" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#ui"><i class="fa fa-check"></i><b>7.6.2</b> UI</a></li>
<li class="chapter" data-level="7.6.3" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#server"><i class="fa fa-check"></i><b>7.6.3</b> Server</a></li>
<li class="chapter" data-level="7.6.4" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#application-generator"><i class="fa fa-check"></i><b>7.6.4</b> Application generator</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#the-simulation-function"><i class="fa fa-check"></i><b>7.7</b> The simulation function</a></li>
<li class="chapter" data-level="7.8" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#the-ui"><i class="fa fa-check"></i><b>7.8</b> The UI</a></li>
<li class="chapter" data-level="7.9" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#the-server"><i class="fa fa-check"></i><b>7.9</b> The server</a></li>
<li class="chapter" data-level="7.10" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#run-the-app"><i class="fa fa-check"></i><b>7.10</b> Run the app</a></li>
<li class="chapter" data-level="7.11" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#what-else-could-we-do"><i class="fa fa-check"></i><b>7.11</b> What else could we do?</a></li>
<li class="chapter" data-level="7.12" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#summary-5"><i class="fa fa-check"></i><b>7.12</b> Summary</a></li>
<li class="chapter" data-level="7.13" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#further-reading-5"><i class="fa fa-check"></i><b>7.13</b> Further Reading</a></li>
<li class="chapter" data-level="7.14" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#practice-laboratory-4"><i class="fa fa-check"></i><b>7.14</b> Practice Laboratory</a><ul>
<li class="chapter" data-level="7.14.1" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#practice-laboratory-1-2"><i class="fa fa-check"></i><b>7.14.1</b> Practice laboratory #1</a></li>
<li class="chapter" data-level="7.14.2" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#practice-laboratory-2-2"><i class="fa fa-check"></i><b>7.14.2</b> Practice laboratory #2</a></li>
</ul></li>
<li class="chapter" data-level="7.15" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#project-3"><i class="fa fa-check"></i><b>7.15</b> Project</a><ul>
<li class="chapter" data-level="7.15.1" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#background-3"><i class="fa fa-check"></i><b>7.15.1</b> Background</a></li>
<li class="chapter" data-level="7.15.2" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#data-3"><i class="fa fa-check"></i><b>7.15.2</b> Data</a></li>
<li class="chapter" data-level="7.15.3" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#workflow-3"><i class="fa fa-check"></i><b>7.15.3</b> Workflow</a></li>
<li class="chapter" data-level="7.15.4" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#assessment-2"><i class="fa fa-check"></i><b>7.15.4</b> Assessment</a></li>
</ul></li>
<li class="chapter" data-level="7.16" data-path="aggregating-enterprise-risk.html"><a href="aggregating-enterprise-risk.html#references-3"><i class="fa fa-check"></i><b>7.16</b> References</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="appendix-1-r-environment-for-financial-analytics.html"><a href="appendix-1-r-environment-for-financial-analytics.html"><i class="fa fa-check"></i><b>8</b> Appendix 1 – R environment for financial analytics</a><ul>
<li class="chapter" data-level="8.1" data-path="appendix-1-r-environment-for-financial-analytics.html"><a href="appendix-1-r-environment-for-financial-analytics.html#setting-up-r-for-analytics"><i class="fa fa-check"></i><b>8.1</b> Setting Up R for Analytics</a><ul>
<li class="chapter" data-level="8.1.1" data-path="appendix-1-r-environment-for-financial-analytics.html"><a href="appendix-1-r-environment-for-financial-analytics.html#motivation"><i class="fa fa-check"></i><b>8.1.1</b> Motivation</a></li>
<li class="chapter" data-level="8.1.2" data-path="appendix-1-r-environment-for-financial-analytics.html"><a href="appendix-1-r-environment-for-financial-analytics.html#some-useful-r-resources"><i class="fa fa-check"></i><b>8.1.2</b> Some useful <code>R</code> resources</a></li>
<li class="chapter" data-level="8.1.3" data-path="appendix-1-r-environment-for-financial-analytics.html"><a href="appendix-1-r-environment-for-financial-analytics.html#install-r-on-your-computer"><i class="fa fa-check"></i><b>8.1.3</b> Install <code>R</code> on your computer</a></li>
<li class="chapter" data-level="8.1.4" data-path="appendix-1-r-environment-for-financial-analytics.html"><a href="appendix-1-r-environment-for-financial-analytics.html#install-rstudio"><i class="fa fa-check"></i><b>8.1.4</b> Install <code>RStudio</code></a></li>
<li class="chapter" data-level="8.1.5" data-path="appendix-1-r-environment-for-financial-analytics.html"><a href="appendix-1-r-environment-for-financial-analytics.html#install-r-markdown"><i class="fa fa-check"></i><b>8.1.5</b> Install <code>R Markdown</code></a></li>
<li class="chapter" data-level="8.1.6" data-path="appendix-1-r-environment-for-financial-analytics.html"><a href="appendix-1-r-environment-for-financial-analytics.html#install-latex"><i class="fa fa-check"></i><b>8.1.6</b> Install LaTex</a></li>
<li class="chapter" data-level="8.1.7" data-path="appendix-1-r-environment-for-financial-analytics.html"><a href="appendix-1-r-environment-for-financial-analytics.html#r-markdown"><i class="fa fa-check"></i><b>8.1.7</b> R Markdown</a></li>
<li class="chapter" data-level="8.1.8" data-path="appendix-1-r-environment-for-financial-analytics.html"><a href="appendix-1-r-environment-for-financial-analytics.html#jargon"><i class="fa fa-check"></i><b>8.1.8</b> jaRgon</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="appendix-1-r-environment-for-financial-analytics.html"><a href="appendix-1-r-environment-for-financial-analytics.html#nomenclature"><i class="fa fa-check"></i><b>8.2</b> Nomenclature</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html"><i class="fa fa-check"></i><b>9</b> Appendix: useful financial concepts</a><ul>
<li class="chapter" data-level="9.0.1" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#a-question-is-raised"><i class="fa fa-check"></i><b>9.0.1</b> A question is raised</a></li>
<li class="chapter" data-level="9.0.2" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#jacob-bernoulli-has-a-story-to-tell"><i class="fa fa-check"></i><b>9.0.2</b> Jacob Bernoulli has a story to tell</a></li>
<li class="chapter" data-level="9.0.3" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#wheres-the-finance"><i class="fa fa-check"></i><b>9.0.3</b> Where’s the finance?</a></li>
<li class="chapter" data-level="9.0.4" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#the-answer-please"><i class="fa fa-check"></i><b>9.0.4</b> The answer please?</a></li>
<li class="chapter" data-level="9.1" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#net-present-value"><i class="fa fa-check"></i><b>9.1</b> Net present value</a><ul>
<li class="chapter" data-level="9.1.1" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#what-is-net-present-value"><i class="fa fa-check"></i><b>9.1.1</b> What is net present value?</a></li>
<li class="chapter" data-level="9.1.2" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#what-do-companies-typically-use-it-for"><i class="fa fa-check"></i><b>9.1.2</b> What do companies typically use it for?</a></li>
<li class="chapter" data-level="9.1.3" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#how-can-we-calculate-npv"><i class="fa fa-check"></i><b>9.1.3</b> How can we calculate NPV?</a></li>
<li class="chapter" data-level="9.1.4" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#what-can-go-wrong"><i class="fa fa-check"></i><b>9.1.4</b> What can go wrong?</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#internal-rate-of-return"><i class="fa fa-check"></i><b>9.2</b> Internal rate of return</a><ul>
<li class="chapter" data-level="9.2.1" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#what-is-the-internal-rate-of-return"><i class="fa fa-check"></i><b>9.2.1</b> What is the internal rate of return?</a></li>
<li class="chapter" data-level="9.2.2" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#how-can-we-calculate-irr"><i class="fa fa-check"></i><b>9.2.2</b> How can we calculate IRR?</a></li>
<li class="chapter" data-level="9.2.3" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#what-can-go-wrong-1"><i class="fa fa-check"></i><b>9.2.3</b> What can go wrong?</a></li>
<li class="chapter" data-level="9.2.4" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#what-is-the-foreign-exchange-market"><i class="fa fa-check"></i><b>9.2.4</b> What is the foreign exchange market?</a></li>
<li class="chapter" data-level="9.2.5" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#what-are-exchange-rates"><i class="fa fa-check"></i><b>9.2.5</b> What are exchange rates?</a></li>
<li class="chapter" data-level="9.2.6" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#what-is-a-foreign-exchange-arrbitrage"><i class="fa fa-check"></i><b>9.2.6</b> What is a foreign exchange arrbitrage?</a></li>
<li class="chapter" data-level="9.2.7" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#how-can-you-hedge-with-foreign-exchange"><i class="fa fa-check"></i><b>9.2.7</b> How can you hedge with foreign exchange?</a></li>
<li class="chapter" data-level="9.2.8" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#covered-interest-arbitrage"><i class="fa fa-check"></i><b>9.2.8</b> Covered interest arbitrage</a></li>
<li class="chapter" data-level="9.2.9" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#what-are-exchange-rate-movements"><i class="fa fa-check"></i><b>9.2.9</b> What are exchange rate movements?</a></li>
<li class="chapter" data-level="9.2.10" data-path="appendix-useful-financial-concepts.html"><a href="appendix-useful-financial-concepts.html#how-can-financial-services-benefit"><i class="fa fa-check"></i><b>9.2.10</b> How can financial services benefit?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references-4.html"><a href="references-4.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Financial Analytics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="portfolio-analytics" class="section level1">
<h1><span class="header-section-number">Chapter 6</span> Portfolio Analytics</h1>
<blockquote>
<p>The first stage starts with observation and experience and ends with beliefs about the future performances of available securities. The second stage starts with the relevant beliefs about future performances and ends with the choice of portfolio. <em>Harry Markowitz</em></p>
</blockquote>
<div id="imagine-this-4" class="section level2">
<h2><span class="header-section-number">6.1</span> Imagine This</h2>
<ul>
<li>You are trying to negotiate a new energy contract across 10 different facilities and 20 gas and oil suppliers.</li>
<li>Your colleague is managing accounts receivable across 38 different currencies in spot and forward markets.</li>
<li>Another colleague manages collateral for workers’ compensation funding in all 50 states.</li>
<li>Yet another colleague manages 5 fund managers for a health insurer.</li>
</ul>
<p>Portfolios are everywhere! We can conceive of every margin as a long position in revenue and a short position in costs. In all case of interest at least some notion of the the mean (central tendency) and standard deviation (scale and diffusion) of a portfolio metric (e.g., return) will be traded off. Operational and financial constraints will narrow the possible choices to achieve performance (mean = “mu” = <span class="math inline">\(\mu\)</span>) and risk (standard deviation = “sigma” = <span class="math inline">\(\sigma\)</span>) goals.</p>
<div id="our-working-example" class="section level3">
<h3><span class="header-section-number">6.1.1</span> Our “working example”</h3>
<p>This will we Working Capital which is Receivables + Inventory - Payables. The CFO needs answers around why it is so big and always seems to bulge when the economic fortunes of our customers are in peril of deteriorating. She knows that there are three culprits: the euro rate, the Sterling rate, and Brent crude. She commissions you and your team to figure out the ultimate combination of these factors that contributes to a $100 million working capital position with a volatility of over $25 million this past year.</p>
</div>
<div id="this-chapter" class="section level3">
<h3><span class="header-section-number">6.1.2</span> This chapter</h3>
<p>The goal of this chapter is to introduce portfolio analytics and incorporate our knowledge of statistics, optimization, and financial objects into the analysis.</p>
</div>
</div>
<div id="lets-walk-before-we-run" class="section level2">
<h2><span class="header-section-number">6.2</span> Let’s Walk Before We Run</h2>
<p>Suppose management wants to achieve a targeted value at risk on new contracts. The value at risk (VaR) is the <span class="math inline">\(\alpha\)</span> quantile of portfolio value where <span class="math inline">\(\alpha\)</span> (“alpha”) is the organization’s tolerance for risk. While VaR is the maximum amount of tolerable loss more loss is possible.</p>
<p>Now suppose Management is considering a $1 billion contract with two Iberian companies and one United Kingdom-based (UK) company working in Spain. The deal is constrained by having $100 million in reserves are available to cover any losses. The Board wants some comfort that no more than a 10 % age loss (the average “return” <span class="math inline">\(\mu\)</span>) would occur. The Board has set the organization’s tolerance for risk at 5%. This means in this case a maximum of 5% of the time could losses exceed 10%. To keep things simple at first we assume that losses are normally distributed.</p>
<p>Let’s perform a “back of the envelope” analysis. We let <span class="math inline">\(R\)</span> stand for returns, so that <span class="math inline">\(-R\)</span> is a loss. Our management team wants</p>
<p><span class="math display">\[
Prob(R &lt; -0.10) = 0.05,
\]</span></p>
<p>that is, the probability of a loss worse than 10 % is no more than 5 %.</p>
<p>Let’s now do some algebra and first let <span class="math inline">\(w\)</span> be the “weight” invested in the risky contract. The rest of the proportion of the contract, <span class="math inline">\(1-w\)</span>, is in high quality collateral assets like treasury bonds. The weight <span class="math inline">\(w\)</span> can take on values from 0% (0.0) to 100% (1.0).</p>
<ul>
<li>No collateral means <span class="math inline">\(w = 1\)</span></li>
<li>No contract means <span class="math inline">\(w = 0\)</span>.</li>
</ul>
<p>The average return, <span class="math inline">\(\mu\)</span>, on the contract is</p>
<p><span class="math display">\[
\mu = w(0.1) + (1-w)(0.02).
\]</span></p>
<p>This is the weighted <em>average</em> return of the contract at 10% and collateral at 2%.</p>
<p>The average level of risk in this model is given by the standard deviation of this combination of risky contract and default-free collateral.</p>
<p>Management currently believes that a 25% standard deviation of return on the contract, “sigma” or <span class="math inline">\(\sigma\)</span>, is reasonable. Collateral is not “risky” in this scenario and thus its standard deviation is zero (and by definition is not correlated with the contract return).</p>
<p><span class="math display">\[
\sigma = w^2 (0.25)^2 + (1-w)^2 (0.0).
\]</span></p>
<p>We now try to figure out what <span class="math inline">\(w\)</span> is. More precisely, we solve for the percentage of total assets as investment in this contract, that will make losses happen no greater than 5% of the time.</p>
<p>We form a normalizing “z-score” to help us. We shift the largest possible loss to average return to a deviation around the 10% loss, then divide by <span class="math inline">\(\sigma\)</span> to scale losses to the number of standard deviations around the maximum tolerable loss.</p>
<p><span class="math display">\[
z = \frac{-0.1 - \mu}{\sigma}.
\]</span></p>
<p>The <span class="math inline">\(z\)</span> the ratio of potential deviation of loss from the mean maximum loss per unit of risk. It is dimensionless and represents the number of standard deviations of loss around the maximum tolerable loss. Our job is to find <span class="math inline">\(w\)</span> such that the <span class="math inline">\(z\)</span> score under the normal distribution cannot exceed 5%.</p>
<p><span class="math display">\[
Prob(R &lt; -0.10) = Normal(z(w)) = 0.05,
\]</span></p>
<p>where <span class="math inline">\(Normal\)</span> is the cumulative normal distribution (you might know this as =Norm.S.Dist() in Excel or <code>qnorm()</code> in <code>R</code>), with mean of zero and standard deviation of one.</p>
<p>Using our models of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> we get</p>
<p><span class="math display">\[
z = \frac{-0.1 - 0.1 w - 0.02 (1-w)}{0.25 w}
\]</span></p>
<p>After combining constant terms and terms in <span class="math inline">\(w\)</span> and putting this into the target probability:</p>
<p><span class="math display">\[
z = Normal \left[ \frac{-0.12 - 0.12 w}{0.25 w} \right] = 0.05.
\]</span></p>
<p>Finally, we solve for <span class="math inline">\(w\)</span> in a few more steps.</p>
<ol style="list-style-type: decimal">
<li>We invert the normal distribution on both sides of the equation. On the left hand side we are left with the <span class="math inline">\(z\)</span> score as a function of <span class="math inline">\(w\)</span>, the percentage of all wealth in the risk contract.
<span class="math display">\[
Inverse \, Normal \left[ Normal \left( \frac{-0.12 - 0.12 w}{0.25 w} \right) \right] = Inverse \, Normal (0.05)
\]</span>
We can calculate <span class="math inline">\(Inverse \, Normal(0.05)\)</span> using <code>R</code></li>
</ol>
<div class="sourceCode" id="cb379"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb379-1" title="1"><span class="kw">qnorm</span>(<span class="fl">0.05</span>)</a></code></pre></div>
<pre><code>## [1] -1.645</code></pre>
<p>or in Excel with <code>=NORM.S.INV(0.05)</code>. Each of these takes as input the probability under the normal distribution and calculates the <span class="math inline">\(z\)</span> score associated with the probability.</p>
<ol start="2" style="list-style-type: decimal">
<li>We find that <code>qnorm(0.05)</code> is 1.64. Loss cannot exceed 1.64 times the portfolio standard deviation in the direction of loss (“negative” or less than the mean) using a one-tail interval. We justify a one-tail interval since we, and the Board, are only interested in loss. Inserting this value we get</li>
</ol>
<p><span class="math display">\[
\left( \frac{-0.12 - 0.12 w}{0.25 w} \right) = NormalInverse (0.05) = -1.64
\]</span></p>
<p>Multiplying each side by <span class="math inline">\(0.25 w\)</span>, combining terms in <span class="math inline">\(w\)</span> and dividing by the coefficient of that last combined <span class="math inline">\(w\)</span> we get</p>
<p><span class="math display">\[
w = \frac{-0.12}{0.25(-1.64) + 0.12} = 0.42.
\]</span></p>
<p>In <code>R</code>:</p>
<div class="sourceCode" id="cb381"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb381-1" title="1"><span class="fl">0.413793103</span></a></code></pre></div>
<pre><code>## [1] 0.4138</code></pre>
<p>Implications?</p>
<ul>
<li>42% of portfolio value = risky contract value.</li>
<li>Portfolio value = $1 billion / 0.42 = $2.38 billion.</li>
<li>Collateral value = $2.38 billion - $1 billion = $1.38 billion or 68% of portfolio value.</li>
</ul>
<p>We just found the notorious “tangency” portfolio. This portfolio, when combined with a risk-free (really “default-free” asset), will yield the best mix of risky and risk-free assets. “Best” here is in the sense of not violating the organization’s risk tolerance policy.</p>
<p>A way to find the tangency portfolio in any situation is then to</p>
<ol style="list-style-type: decimal">
<li>Find the optimal combination of risky assets, the tangency portfolio.</li>
<li>Then find the optimal mix of tangency assets and the risk-free asset.</li>
</ol>
<p>In our example working capital’s “risk-free” asset is the cash account and the process of getting there is the cash-conversion cycle.</p>
</div>
<div id="all-in" class="section level2">
<h2><span class="header-section-number">6.3</span> All In</h2>
<p>Now that we have our basic procedure, let’s complicate this problem with many risky assets. The basic solution will be choosing weights to minimize the portfolio risk given risk-adjusted return targets. This is the Markowitz (1952) portfolio solution. For this task we need to define a matrix version of the portfolio allocation problem. Our three risky “assets” will be the euro/USD and GBP/USD exchange rates and Brent crude.</p>
<p>This is all about the normally distributed universe. Let’s define more precisely</p>
<p>First, the return matrix <span class="math inline">\(R\)</span> for <span class="math inline">\(N\)</span> assets across <span class="math inline">\(T\)</span> sample periods and the subscript indicates the row (observation) and column (asset):</p>
<p><span class="math display">\[ 
\left[ \begin{array}{ccc}
R_{11} &amp; ... &amp; R_{1N}  \\
... &amp; ... &amp; ... \\
R_{1T} &amp; ... &amp; R_{TN} 
\end{array} \right]
\]</span></p>
<p>Then, the mean return vector <span class="math inline">\(\mu\)</span> is the arithmetic average of each column of <span class="math inline">\(R\)</span></p>
<p><span class="math display">\[ 
\left[ \begin{array}{c}
\mu_1  \\
... \\
\mu_N 
\end{array} \right],
\]</span></p>
<p>after exchanging rows for columns (transpose).</p>
<div id="try-this-exercise-8" class="section level3">
<h3><span class="header-section-number">6.3.1</span> Try this exercise</h3>
<p>First let’s be sure the <code>qrmdata</code> package is installed. We require this package and the daily data in it. Then we will look up the <code>apply</code> function to see how we can compute row averages.</p>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb383-1" title="1"><span class="kw">require</span>(qrmdata)</a>
<a class="sourceLine" id="cb383-2" title="2"><span class="kw">require</span>(xts)</a>
<a class="sourceLine" id="cb383-3" title="3"><span class="co">## The exchange rate data was obtained from OANDA (http://www.oanda.com/) on 2016-01-03</span></a>
<a class="sourceLine" id="cb383-4" title="4"><span class="kw">data</span>(<span class="st">&quot;EUR_USD&quot;</span>)</a>
<a class="sourceLine" id="cb383-5" title="5"><span class="kw">data</span>(<span class="st">&quot;GBP_USD&quot;</span>)</a>
<a class="sourceLine" id="cb383-6" title="6"><span class="co">## The Brent data was obtained from Federal Reserve Economic Data (FRED) via Quandl on 2016-01-03</span></a>
<a class="sourceLine" id="cb383-7" title="7"><span class="kw">data</span>(<span class="st">&quot;OIL_Brent&quot;</span>)</a>
<a class="sourceLine" id="cb383-8" title="8">data<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">na.omit</span>(<span class="kw">merge</span>(EUR_USD, GBP_USD, OIL_Brent))</a>
<a class="sourceLine" id="cb383-9" title="9">R &lt;-<span class="st"> </span><span class="kw">na.omit</span>(<span class="kw">diff</span>(<span class="kw">log</span>(data<span class="fl">.1</span>))<span class="op">*</span><span class="dv">100</span>)</a>
<a class="sourceLine" id="cb383-10" title="10">names.R &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;EUR.USD&quot;</span>, <span class="st">&quot;GBP.USD&quot;</span>, <span class="st">&quot;OIL.Brent&quot;</span>)</a>
<a class="sourceLine" id="cb383-11" title="11"><span class="kw">colnames</span>(R) &lt;-<span class="st"> </span>names.R</a></code></pre></div>
<p>First we compute the mean return.</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb384-1" title="1">(mean.R &lt;-<span class="st"> </span><span class="kw">apply</span>(R, <span class="dv">2</span>, mean))</a></code></pre></div>
<pre><code>##   EUR.USD   GBP.USD OIL.Brent 
##  0.001539 -0.002283  0.010774</code></pre>
<p>Now some questions for us to consider:</p>
<ol style="list-style-type: decimal">
<li>Let’s look at a <code>summary</code> of a few columns. Is there anything odd or curious?</li>
<li>What does the <code>2</code> indicate in the <code>apply</code> function.</li>
<li>What is Brent crude’s annualized mean “return”?</li>
</ol>
<p>Some immediate results ensue.</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb386-1" title="1"><span class="kw">summary</span>(R)</a></code></pre></div>
<pre><code>##      Index               EUR.USD          GBP.USD         OIL.Brent      
##  Min.   :2000-01-05   Min.   :-2.523   Min.   :-4.648   Min.   :-19.891  
##  1st Qu.:2003-12-18   1st Qu.:-0.308   1st Qu.:-0.278   1st Qu.: -1.153  
##  Median :2007-12-05   Median : 0.014   Median : 0.006   Median :  0.036  
##  Mean   :2007-12-19   Mean   : 0.002   Mean   :-0.002   Mean   :  0.011  
##  3rd Qu.:2011-12-19   3rd Qu.: 0.322   3rd Qu.: 0.287   3rd Qu.:  1.249  
##  Max.   :2015-12-28   Max.   : 3.464   Max.   : 3.141   Max.   : 18.130</code></pre>
<p>Means are much less than medians. There are juge maximum and minimum returns. We can also look at <code>acf</code> and <code>ccf</code>, absolute returns, run GARCH models, and so on to hone our exploratory analysis.</p>
<p>We ook up <code>??apply</code> and read that the <code>2</code> indicates that we are calculating the mean for the second dimension of the data matrix, namely, the assets.</p>
<p>Brent crude’s annualized mean return is calculated on a 252 average days traded in a year basis as:</p>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb388-1" title="1">(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>mean.R[<span class="dv">3</span>]<span class="op">/</span><span class="dv">100</span>)<span class="op">^</span><span class="dv">252</span> <span class="op">-</span><span class="st"> </span><span class="dv">1</span></a></code></pre></div>
<pre><code>## OIL.Brent 
##   0.02752</code></pre>
<p>Some folks use 253 days. But this is all a back of the envelope computation.</p>
</div>
<div id="lets-keep-moving-on" class="section level3">
<h3><span class="header-section-number">6.3.2</span> Let’s keep moving on…</h3>
<p>So, what is the context? We have working capital with three main drivers of risk and return: two exchange rates and a commodity price. Over time we will want to know how these factors act and interact to produce EBITDA returns on Assets. Here EBITDA is Earnings Before Interest and Tax adding back in non-cash Depreciation and Amortization.</p>
<blockquote>
<p>Then, how does that combination compare with today’s reality and especially answer the CFO’s question of what to do about the millstone of working capital around the neck of EBITDA?</p>
</blockquote>
<p>Given this context, and the data we found earlier on, we then calculate the variance-covariance matrix. The diagonals of this matrix are the variances, so that the square root of the diagonal will yield standard deviations. The off-diagonals can be converted to correlations as needed.</p>
<div class="sourceCode" id="cb390"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb390-1" title="1">(mean.R &lt;-<span class="st">  </span><span class="kw">apply</span>(R,<span class="dv">2</span>,mean))</a></code></pre></div>
<pre><code>##   EUR.USD   GBP.USD OIL.Brent 
##  0.001539 -0.002283  0.010774</code></pre>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb392-1" title="1">(cov.R &lt;-<span class="st">  </span><span class="kw">cov</span>(R))</a></code></pre></div>
<pre><code>##           EUR.USD GBP.USD OIL.Brent
## EUR.USD    0.3341  0.1939    0.1631
## GBP.USD    0.1939  0.2539    0.1809
## OIL.Brent  0.1631  0.1809    5.0572</code></pre>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb394-1" title="1">(sd.R &lt;-<span class="st">  </span><span class="kw">sqrt</span>(<span class="kw">diag</span>(cov.R))) <span class="co">## remember these are in daily percentages</span></a></code></pre></div>
<pre><code>##   EUR.USD   GBP.USD OIL.Brent 
##    0.5780    0.5039    2.2488</code></pre>
<p>Now for some programming (quadratic that is…) but first let’s get more mathematical about the statement of the problem we are about to solve. In a mathematical nutshell we are formally (more tractable version to follow…) solving the problem of minimizing working capital factors risk, subject to target returns and a budget that says it all has to add up to our working capital position. We define weights as percentages of the total working capital position. Thus the weights need to add up to one.</p>
<p><span class="math display">\[
\begin{array}{c}
min_w w_T \Sigma w \\
subject \, to \\
1^T w = 1\\
w^T \mu = \mu_0
\end{array}
\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(w\)</span> are the weights in each instrument.</li>
<li><span class="math inline">\(\Sigma\)</span> is the variance-covariance matrix we just estimated, <code>cov.R</code>.</li>
<li><span class="math inline">\(1\)</span> is a vector of ones’s with length equal to the number of instruments.</li>
<li><span class="math inline">\(\mu\)</span> are the mean returns we just estimated, <code>mean.R</code>.</li>
<li><span class="math inline">\(\mu_0\)</span> is the target portfolio return.</li>
<li><span class="math inline">\(T\)</span> is the matrix transpose.</li>
<li><span class="math inline">\(min_w\)</span> means to find weights <span class="math inline">\(w\)</span> that minimizes portfolio risk.</li>
</ul>
<p>The expression <span class="math inline">\(w_T \Sigma w\)</span> is our measure of portfolio risk and is a quadratic form that looks like this for two instruments:</p>
<p><span class="math display">\[
\left[ \begin{array}{cc} w_1 &amp; w_2 \end{array} \right] \left[ \begin{array}{cc} \sigma_1^2 &amp; \sigma_{12} \\ \sigma_{21} &amp; \sigma_2^2 \end{array} \right] \left[ \begin{array}{c} w_1 \\ w_2 \end{array} \right]
\]</span></p>
<p>Multiplied out we get the following quadratic formula for portfolio variance:</p>
<p><span class="math display">\[
\sigma_P^2 = w_1^2 \sigma_1^2 + w_2^2 \sigma_2^2 + w_1 w_2 \sigma_{12} + w_2 w_1 \sigma_{21}  
\]</span></p>
<p>and because <span class="math inline">\(\sigma_{12} = \sigma_{21}\)</span> this reduces a bit to</p>
<p><span class="math display">\[
\sigma_P^2 = w_1^2 \sigma_1^2 + w_2^2 \sigma_2^2 + 2 w_1 w_2 \sigma_{12}
\]</span></p>
<p>Tedious? Definitely. But useful to explain the components of portfolio risk</p>
<ol style="list-style-type: decimal">
<li>Two dashes of own asset risk <span class="math inline">\(w_1^2 \sigma_1^2 + w_2^2 \sigma_2^2\)</span>, and</li>
<li>Two dashes of relational risk <span class="math inline">\(2 w_1 w_2 \sigma_{12}\)</span></li>
</ol>
<p>When <span class="math inline">\(\sigma_{12} &lt; 1\)</span> we have <em>diversification</em>.</p>
</div>
<div id="try-this-exercise-9" class="section level3">
<h3><span class="header-section-number">6.3.3</span> Try this exercise</h3>
<p>Suppose we have two commodities (New York Harbor No. 2 Oil and Henry Hub Natural Gas) feeding a production process (Electricity Generation).These are the weights in this process:
<span class="math display">\[
w = \{ w_{oil} = -.5, w_{ng} = -.5, w_{ele} = 1.0 \}
\]</span>
The percentage changes in terms of the prices of these commodities are given by:
<span class="math display">\[
\mu = \{ \mu_{oil} = 0.12, \mu_{ng} = -0.09, \mu_{ele} = 0.15 \}.
\]</span>
Standard deviations are
<span class="math display">\[
\sigma = \{ \sigma_{oil} = 0.20, \sigma_{ng} = 0.15, \sigma_{ele} = 0.40 \}
\]</span>
The correlation matrix is
<span class="math display">\[
\rho = 
\left[ \begin{array}{ccc}
1.0 &amp; 0.2 &amp; 0.6  \\
0.2 &amp; 1.0 &amp; 0.4 \\
0.6 &amp; 0.4 &amp; 1.0 
\end{array} \right]
\]</span>
Using the formula
<span class="math display">\[
\Sigma = (\sigma \sigma^T) \rho
\]</span>
we can calculate the variance-covariance matrix <span class="math inline">\(\Sigma\)</span> using our <code>R</code> knowledge of arrays. [Hint: <code>t()</code> is the transpose of an array so that <span class="math inline">\(\sigma^T\)</span> is <code>t(sigma)</code>.] We can also calculate the portfolio mean return and portfolio standard deviation.</p>
<p>Let’s Use this <code>R</code> code to put all of this into action.</p>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb396-1" title="1">sigma &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.20</span>, <span class="fl">0.15</span>, <span class="fl">0.40</span>)</a>
<a class="sourceLine" id="cb396-2" title="2">rho =<span class="st"> </span><span class="kw">c</span>(<span class="fl">1.0</span> , <span class="fl">0.2</span> , <span class="fl">0.6</span>,</a>
<a class="sourceLine" id="cb396-3" title="3"><span class="fl">0.2</span> , <span class="fl">1.0</span> , <span class="fl">0.4</span>,</a>
<a class="sourceLine" id="cb396-4" title="4"><span class="fl">0.6</span> , <span class="fl">0.4</span> , <span class="fl">1.0</span> )</a>
<a class="sourceLine" id="cb396-5" title="5">(rho &lt;-<span class="st"> </span><span class="kw">matrix</span>(rho, <span class="dt">nrow =</span> <span class="dv">3</span>, <span class="dt">ncol =</span> <span class="dv">3</span>))</a></code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]  1.0  0.2  0.6
## [2,]  0.2  1.0  0.4
## [3,]  0.6  0.4  1.0</code></pre>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb398-1" title="1">(Sigma2 &lt;-<span class="st"> </span>(sigma <span class="op">%*%</span><span class="st"> </span><span class="kw">t</span>(sigma)) <span class="op">*</span><span class="st"> </span>rho )</a></code></pre></div>
<pre><code>##       [,1]   [,2]  [,3]
## [1,] 0.040 0.0060 0.048
## [2,] 0.006 0.0225 0.024
## [3,] 0.048 0.0240 0.160</code></pre>
<p>The diagonals are the squared standard deviations. Next we tackle the portfolio average rate.</p>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb400-1" title="1">w &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="op">-</span><span class="fl">0.5</span>, <span class="fl">-0.5</span>, <span class="fl">1.0</span>)</a>
<a class="sourceLine" id="cb400-2" title="2">mu &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="fl">0.12</span>, <span class="fl">-0.09</span>, <span class="fl">0.15</span>)</a>
<a class="sourceLine" id="cb400-3" title="3">(mu.P &lt;-<span class="st"> </span><span class="kw">t</span>(w) <span class="op">%*%</span><span class="st"> </span>mu)</a></code></pre></div>
<pre><code>##       [,1]
## [1,] 0.135</code></pre>
<p>Now we compute the portfolio average level of “risk”.</p>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb402-1" title="1">(Sigma.P &lt;-<span class="st"> </span>(<span class="kw">t</span>(w) <span class="op">%*%</span><span class="st"> </span>Sigma2 <span class="op">%*%</span><span class="st"> </span>w))<span class="op">^</span><span class="fl">0.5</span></a></code></pre></div>
<pre><code>##        [,1]
## [1,] 0.3265</code></pre>
<p>What does all of this mean?</p>
<ul>
<li>Running a power-generating plant (or refinery, or distribution chain, …) over time financially really means generating a spark spread: the margin between costs of inputs natural gas and oil (the negative or short position) and revenue from the output</li>
<li>The average spark spread rate of return for this plant is 10.67%. The spark spread is the difference between the price of electricity and the price of input fuels on a MWh basis (megawatt-hour).</li>
<li>The standard deviation of the spark spread is 32.65%.</li>
</ul>
<p>Our next job is to use these mechanics about portfolio means, standard deviations, and correlations to find the best set of weights that minimizes portfolio risk while attempting to achieve a target level of return.</p>
</div>
</div>
<div id="optimizing-a-portfolio" class="section level2">
<h2><span class="header-section-number">6.4</span> Optimizing a Portfolio</h2>
<p>To perform the optimization task we turn to the <code>quadprog</code> quadratic programming package (yes, parabolas are indeed very useful). We worked out a two-asset example that showed us clearly that the objective function has squared terms (and interactive product terms too). These are the tell-tale signs that mark the portfolio variance as quadratic. It is all in the weights.</p>
<p>After all of our wrangling above it is useful to define our portfolio optimization problem again here:</p>
<p><span class="math display">\[
\begin{array}{c}
min_{(w)} w_T \Sigma w \\
subject \, to \\
1^T w = 1\\
w^T \mu = \mu_0
\end{array}
\]</span>
On the other hand here is what <code>quadprog</code> does in its native format.
<span class="math display">\[
\begin{array}{c}
min_d -d^T x +\frac{1}{2} x^T D x \\
subject \, to \\
A_{neq}^T x \geq b_{neq} \\
A_{eq}^T x = b_{eq}
\end{array}
\]</span>
Now we need to transform these equations into portfolio paramters to solve our portfolio problem. We do this by setting
<span class="math display">\[
A_{eq}^T = \left[ 
\begin{array}{c}
1^T \\
\mu^T
\end{array}
\right]
\]</span>
This gives us a stack of equality constraints that looks like:
<span class="math display">\[
\left[ \begin{array}{c}
1^T w \\
\mu^T w
\end{array}
\right]
=
\left[ \begin{array}{c}
1 \\
\mu_0
\end{array}
\right]
\]</span>
We will allow short positions, like the spark spread experiment above. This means we will not yet impose inequality constraints like <span class="math inline">\(w \geq 0\)</span>.</p>
<p>Here is the setup code</p>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb404-1" title="1"><span class="kw">library</span>(quadprog)</a>
<a class="sourceLine" id="cb404-2" title="2">Amat &lt;-<span class="st">  </span><span class="kw">cbind</span>(<span class="kw">rep</span>(<span class="dv">1</span>,<span class="dv">3</span>),mean.R)  <span class="co">## set the equality constraints matrix</span></a>
<a class="sourceLine" id="cb404-3" title="3">mu.P &lt;-<span class="st">  </span><span class="kw">seq</span>(<span class="kw">min</span>(mean.R <span class="op">-</span><span class="st"> </span><span class="fl">0.0005</span>), <span class="kw">max</span>(mean.R <span class="op">+</span><span class="st"> </span><span class="fl">0.0005</span>), <span class="dt">length=</span><span class="dv">300</span>)  <span class="co">## set of 300 possible target portfolio returns</span></a>
<a class="sourceLine" id="cb404-4" title="4">sigma.P &lt;-<span class="st">  </span>mu.P <span class="co">## set up storage for std dev&#39;s of portfolio returns</span></a>
<a class="sourceLine" id="cb404-5" title="5">weights &lt;-<span class="st">  </span><span class="kw">matrix</span>(<span class="dv">0</span>, <span class="dt">nrow=</span><span class="dv">300</span>, <span class="dt">ncol =</span> <span class="kw">ncol</span>(R)) <span class="co">## storage for portfolio weights</span></a>
<a class="sourceLine" id="cb404-6" title="6"><span class="kw">colnames</span>(weights) &lt;-<span class="st"> </span>names.R</a></code></pre></div>
<p>Next we build the “efficient frontier.” This curve (a parabola…) traces optimal combinations of risk and return. For each combination there is an underlying set of weights calculated in successive optimizations, one for each target <span class="math inline">\(\mu\)</span>. In effect this is a very specialized sensitivity analysis.</p>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb405-1" title="1"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(mu.P))</a>
<a class="sourceLine" id="cb405-2" title="2">{</a>
<a class="sourceLine" id="cb405-3" title="3">  bvec =<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,mu.P[i])  <span class="co">## constraint vector</span></a>
<a class="sourceLine" id="cb405-4" title="4">  result =</a>
<a class="sourceLine" id="cb405-5" title="5"><span class="st">    </span><span class="kw">solve.QP</span>(<span class="dt">Dmat=</span><span class="dv">2</span><span class="op">*</span>cov.R,<span class="dt">dvec=</span><span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">3</span>),<span class="dt">Amat=</span>Amat,<span class="dt">bvec=</span>bvec,<span class="dt">meq=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb405-6" title="6">  sigma.P[i] =<span class="st"> </span><span class="kw">sqrt</span>(result<span class="op">$</span>value)</a>
<a class="sourceLine" id="cb405-7" title="7">  weights[i,] =<span class="st"> </span>result<span class="op">$</span>solution</a>
<a class="sourceLine" id="cb405-8" title="8">}</a></code></pre></div>
<p>First, we plot all of the portfolio combinations.</p>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb406-1" title="1"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</a>
<a class="sourceLine" id="cb406-2" title="2"><span class="kw">plot</span>(sigma.P, mu.P, <span class="dt">type=</span><span class="st">&quot;l&quot;</span>, <span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(sd.R)<span class="op">*</span><span class="fl">1.1</span>), <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(mean.R)<span class="op">*</span><span class="fl">1.1</span>), <span class="dt">lty=</span><span class="dv">3</span>, <span class="dt">lwd =</span> <span class="dv">3</span>)  <span class="co">##  plot</span></a>
<a class="sourceLine" id="cb406-3" title="3"><span class="co">## the efficient frontier (and inefficient portfolios</span></a>
<a class="sourceLine" id="cb406-4" title="4"><span class="co">## below the min var portfolio)</span></a>
<a class="sourceLine" id="cb406-5" title="5">mu.free =<span class="st"> </span><span class="fl">1.3</span><span class="op">/</span><span class="dv">253</span> <span class="co">## input value of risk-free interest rate</span></a>
<a class="sourceLine" id="cb406-6" title="6"><span class="kw">points</span>(<span class="dv">0</span>,mu.free,<span class="dt">cex=</span><span class="dv">1</span>,<span class="dt">pch=</span><span class="st">&quot;+&quot;</span>)  <span class="co">## show risk-free asset</span></a></code></pre></div>
<p>Then we plot the point on the graph that represents the so-called risk-free (actually more like default-free) asset.
<img src="bookdown-demo_files/figure-html/unnamed-chunk-201-1.png" width="672" />
Finally we deploy William Sharpe’s ratio.</p>
<ul>
<li>This number is the amount of portfolio premium per unit of risk (the “price” of risk) across all combinations of portfolio assets on the efficient frontier. Its maximum is the best combination for the risk in terms of returns.</li>
<li>We figure out where (the index <code>ind</code>) the return to risk is along the frontier, record the weights associated with this unique point in risk-return space, and</li>
<li>We find where (the index <code>ind2</code>) the minimum variance portfolio is.</li>
<li>We then plot the “efficient frontier”: the efficient frontier will extend from the minimum variance portfolio (a “+” will mark the spot) up and out (in red). Anything else below this line is “inefficient” in the sense you get less and less return for mo</li>
</ul>
<p>Here is the code we just built up.</p>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb407-1" title="1">sharpe =( mu.P<span class="op">-</span>mu.free)<span class="op">/</span>sigma.P <span class="co">## compute Sharpe&#39;s ratios</span></a>
<a class="sourceLine" id="cb407-2" title="2">ind =<span class="st"> </span>(sharpe <span class="op">==</span><span class="st"> </span><span class="kw">max</span>(sharpe)) <span class="co">## Find maximum Sharpe&#39;s ratio</span></a>
<a class="sourceLine" id="cb407-3" title="3"><span class="kw">options</span>(<span class="dt">digits=</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb407-4" title="4"><span class="kw">lines</span>(<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">2</span>),mu.free<span class="op">+</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">2</span>)<span class="op">*</span>(mu.P[ind]<span class="op">-</span>mu.free)<span class="op">/</span>sigma.P[ind],<span class="dt">lwd=</span><span class="dv">4</span>,<span class="dt">lty=</span><span class="dv">1</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb407-5" title="5"><span class="co">## show line of optimal portfolios</span></a>
<a class="sourceLine" id="cb407-6" title="6"><span class="kw">points</span>(sigma.P[ind],mu.P[ind],<span class="dt">cex=</span><span class="dv">4</span>,<span class="dt">pch=</span><span class="st">&quot;*&quot;</span>) <span class="co">## show tangency portfolio</span></a>
<a class="sourceLine" id="cb407-7" title="7">ind2 =<span class="st"> </span>(sigma.P <span class="op">==</span><span class="st"> </span><span class="kw">min</span>(sigma.P)) <span class="co">## find the minimum variance portfolio</span></a>
<a class="sourceLine" id="cb407-8" title="8"><span class="kw">points</span>(sigma.P[ind2],mu.P[ind2],<span class="dt">cex=</span><span class="dv">2</span>,<span class="dt">pch=</span><span class="st">&quot;+&quot;</span>) <span class="co">## show min var portfolio</span></a>
<a class="sourceLine" id="cb407-9" title="9">ind3 =<span class="st"> </span>(mu.P <span class="op">&gt;</span><span class="st"> </span>mu.P[ind2]) <span class="co">## finally the efficient frontier</span></a>
<a class="sourceLine" id="cb407-10" title="10"><span class="kw">lines</span>(sigma.P[ind3],mu.P[ind3],<span class="dt">type=</span><span class="st">&quot;l&quot;</span>, <span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(sd.R)<span class="op">*</span><span class="fl">1.1</span>), <span class="dt">ylim=</span><span class="kw">c</span>(<span class="kw">min</span>(mean.R)<span class="op">*</span><span class="fl">1.05</span>, <span class="kw">max</span>(mean.R)<span class="op">*</span><span class="fl">1.1</span>) ,<span class="dt">lwd=</span><span class="dv">3</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)  <span class="co">##  plot the efficient frontier</span></a>
<a class="sourceLine" id="cb407-11" title="11"><span class="kw">text</span>(sd.R[<span class="dv">1</span>],mean.R[<span class="dv">1</span>],<span class="st">&quot;EUR.USD&quot;</span>,<span class="dt">cex=</span><span class="fl">1.15</span>)</a>
<a class="sourceLine" id="cb407-12" title="12"><span class="kw">text</span>(sd.R[<span class="dv">2</span>],mean.R[<span class="dv">2</span>],<span class="st">&quot;GBP.USD&quot;</span>,<span class="dt">cex=</span><span class="fl">1.15</span>)</a>
<a class="sourceLine" id="cb407-13" title="13"><span class="kw">text</span>(sd.R[<span class="dv">3</span>],mean.R[<span class="dv">3</span>],<span class="st">&quot;OIL_Brent&quot;</span>,<span class="dt">cex=</span><span class="fl">1.15</span>)</a></code></pre></div>
<p>Altogether we have these results.</p>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-203-1.png" width="672" /></p>
<p>The weights for the tangency portfolio ("*") are in</p>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb408-1" title="1">weights[ind,]</a></code></pre></div>
<pre><code>##   EUR.USD   GBP.USD OIL.Brent 
##     2.500    -1.807     0.306</code></pre>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb410-1" title="1"><span class="kw">sum</span>(weights[ind,])</a></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>For a given notional amount in your portfolio, go long (buy) 250.% of that position in euros traded against USD, go short (sell) 180.7% of your aggregate position in euros traded against USD, and go long 30.6% in Brent.</p>
<p>This means in the working capital accounts:</p>
<ol style="list-style-type: decimal">
<li>$250 million should be denominated in euros</li>
<li>Net of a short (payables?) position of $180 million</li>
<li>With another $30 million priced in Brent crude.</li>
</ol>
<p>If our working capital is $100 million in euros, -$200 in sterling, and $200 exposed to Brent, we might think of ways to bring this more into line with the optimal positions we just derived, by changing contract terms and using swaps and other derivative instruments.</p>
<div id="try-this-exercise-10" class="section level3">
<h3><span class="header-section-number">6.4.1</span> Try this exercise</h3>
<p>In this scenario we don’t allow short positions (negative weights). This means we impose the inequality constraint:
<span class="math display">\[w \geq 0\]</span>
Further,</p>
<ul>
<li>We modify the <code>Amat</code> to <code>Amat</code> to <code>cbind(rep(1,3),mean.R,diag(1,nrow=3))</code>.</li>
<li>We set the target return vector<code>mu.P</code> to <code>seq(min(mean.R)+.0001, max(mean.R)-.0001, length=300)</code>.</li>
<li>We also set the righthand-side vector <code>bvec</code> to <code>c(1,mu.P[i],rep(0,3))</code>.</li>
</ul>
<p>Let’s watch what happens using these questions as a guide.</p>
<ol style="list-style-type: decimal">
<li>Are the tangency portfolio and minimum variance portfolio weights different?</li>
<li>Explain how the constraint matrix and target return vector are different from the first run where <span class="math inline">\(w\)</span> was allowed to be negative.</li>
</ol>
<p>Here is the new setup code where we no longer allow for short positions.</p>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb412-1" title="1"><span class="kw">library</span>(quadprog)</a>
<a class="sourceLine" id="cb412-2" title="2">Amat &lt;-<span class="st">  </span><span class="kw">cbind</span>(<span class="kw">rep</span>(<span class="dv">1</span>,<span class="dv">3</span>),mean.R,<span class="kw">diag</span>(<span class="dv">1</span>,<span class="dt">nrow=</span><span class="dv">3</span>))  <span class="co">## set the equality ND inequality constraints matrix</span></a>
<a class="sourceLine" id="cb412-3" title="3">mu.P &lt;-<span class="st">  </span><span class="kw">seq</span>(<span class="kw">min</span>(mean.R) <span class="op">+</span><span class="st"> </span><span class="fl">0.0001</span>, <span class="kw">max</span>(mean.R) <span class="op">-</span><span class="st"> </span><span class="fl">0.0001</span>, <span class="dt">length=</span><span class="dv">300</span>)  <span class="co">## set of 300 possible target portfolio returns</span></a>
<a class="sourceLine" id="cb412-4" title="4">sigma.P &lt;-<span class="st">  </span>mu.P <span class="co">## set up storage for std dev&#39;s of portfolio returns</span></a>
<a class="sourceLine" id="cb412-5" title="5">weights &lt;-<span class="st">  </span><span class="kw">matrix</span>(<span class="dv">0</span>,<span class="dt">nrow=</span><span class="dv">300</span>,<span class="dt">ncol=</span><span class="dv">3</span>) <span class="co">## storage for portfolio weights</span></a></code></pre></div>
<p>Next we build the “efficient frontier.” All of this code is as before.</p>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb413-1" title="1"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(mu.P))</a>
<a class="sourceLine" id="cb413-2" title="2">{</a>
<a class="sourceLine" id="cb413-3" title="3">  bvec &lt;-<span class="st">  </span><span class="kw">c</span>(<span class="dv">1</span>,mu.P[i],<span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">3</span>))  <span class="co">## constraint vector with no short positions</span></a>
<a class="sourceLine" id="cb413-4" title="4">  result &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb413-5" title="5"><span class="st">    </span><span class="kw">solve.QP</span>(<span class="dt">Dmat=</span><span class="dv">2</span><span class="op">*</span>cov.R,<span class="dt">dvec=</span><span class="kw">rep</span>(<span class="dv">0</span>,<span class="dv">3</span>),<span class="dt">Amat=</span>Amat,<span class="dt">bvec=</span>bvec,<span class="dt">meq=</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb413-6" title="6">  sigma.P[i] &lt;-<span class="st">  </span><span class="kw">sqrt</span>(result<span class="op">$</span>value)</a>
<a class="sourceLine" id="cb413-7" title="7">  weights[i,] &lt;-<span class="st">  </span>result<span class="op">$</span>solution</a>
<a class="sourceLine" id="cb413-8" title="8">}</a></code></pre></div>
<p>Then we plot, again the same as before.</p>
<ol style="list-style-type: decimal">
<li>Plot all of the portfolio combinations.</li>
<li>Plot the point on the graph that represents the so-called risk-free (actually more like default-free) asset.</li>
</ol>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb414-1" title="1"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</a>
<a class="sourceLine" id="cb414-2" title="2"><span class="kw">plot</span>(sigma.P,mu.P,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(sd.R)<span class="op">*</span><span class="fl">1.1</span>),<span class="dt">ylim=</span><span class="kw">c</span>(<span class="kw">min</span>(mean.R)<span class="op">*</span><span class="fl">1.05</span>, <span class="kw">max</span>(mean.R)<span class="op">*</span><span class="fl">1.1</span>),<span class="dt">lty=</span><span class="dv">3</span>, <span class="dt">lwd =</span> <span class="dv">3</span>)  <span class="co">##  plot the efficient frontier (and inefficient portfolios</span></a>
<a class="sourceLine" id="cb414-3" title="3"><span class="co">## below the min var portfolio)  </span></a>
<a class="sourceLine" id="cb414-4" title="4">mu.free &lt;-<span class="st">  </span><span class="fl">1.3</span><span class="op">/</span><span class="dv">253</span> <span class="co">## input value of risk-free interest rate</span></a>
<a class="sourceLine" id="cb414-5" title="5"><span class="kw">points</span>(<span class="dv">0</span>,mu.free,<span class="dt">cex=</span><span class="fl">1.5</span>,<span class="dt">pch=</span><span class="st">&quot;+&quot;</span>)  <span class="co">## show risk-free asset</span></a></code></pre></div>
<p>And…
<img src="bookdown-demo_files/figure-html/unnamed-chunk-208-1.png" width="672" />
Now for William Sharpe’s ratio, again as before, where</p>
<ul>
<li>This number is the amount of portfolio premium per unit of risk (the “price” of risk) across all combinations of portfolio assets on the efficient frontier. Its maximum is the best combination for the risk in terms of returns.</li>
<li>We figure out where (the index <code>ind</code>) the return to risk is along the frontier, record the weights associated with this unique point in risk-return space, and</li>
<li>Find where (the index <code>ind2</code>) the minimum variance portfolio is.</li>
<li>Plot the “efficient frontier”: the efficient frontier will extend from the minimum variance portfolio (a “+” will mark the spot) up and out (in red). Anything else below this line is “inefficient” in the sense you get less and less return for more and m</li>
</ul>
<p>Here is the code (again) for using Sharpe’s ratio.</p>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb415-1" title="1"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</a>
<a class="sourceLine" id="cb415-2" title="2"><span class="kw">plot</span>(sigma.P,mu.P,<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(sd.R)<span class="op">*</span><span class="fl">1.1</span>),<span class="dt">ylim=</span><span class="kw">c</span>(<span class="kw">min</span>(mean.R)<span class="op">*</span><span class="fl">1.05</span>, <span class="kw">max</span>(mean.R)<span class="op">*</span><span class="fl">1.1</span>),<span class="dt">lty=</span><span class="dv">3</span>, <span class="dt">lwd =</span> <span class="dv">3</span>)  <span class="co">##  plot the efficient frontier (and inefficient portfolios</span></a>
<a class="sourceLine" id="cb415-3" title="3"><span class="co">## below the min var portfolio)  </span></a>
<a class="sourceLine" id="cb415-4" title="4">mu.free &lt;-<span class="st">  </span><span class="fl">1.3</span><span class="op">/</span><span class="dv">253</span> <span class="co">## input value of risk-free interest rate</span></a>
<a class="sourceLine" id="cb415-5" title="5"><span class="kw">points</span>(<span class="dv">0</span>,mu.free, <span class="dt">cex=</span><span class="fl">1.5</span>, <span class="dt">pch=</span><span class="st">&quot;+&quot;</span>)  <span class="co">## show risk-free asset</span></a>
<a class="sourceLine" id="cb415-6" title="6">mu.free &lt;-<span class="st">  </span><span class="fl">1.3</span><span class="op">/</span><span class="dv">253</span> <span class="co">## input value of risk-free interest rate</span></a>
<a class="sourceLine" id="cb415-7" title="7"><span class="kw">points</span>(<span class="dv">0</span>, mu.free, <span class="dt">cex=</span><span class="fl">1.5</span>, <span class="dt">pch=</span><span class="st">&quot;+&quot;</span>)  <span class="co">## show risk-free asset</span></a>
<a class="sourceLine" id="cb415-8" title="8">sharpe =( mu.P<span class="op">-</span>mu.free)<span class="op">/</span>sigma.P <span class="co">## compute Sharpe&#39;s ratios</span></a>
<a class="sourceLine" id="cb415-9" title="9">ind =<span class="st"> </span>(sharpe <span class="op">==</span><span class="st"> </span><span class="kw">max</span>(sharpe)) <span class="co">## Find maximum Sharpe&#39;s ratio</span></a>
<a class="sourceLine" id="cb415-10" title="10"><span class="kw">options</span>(<span class="dt">digits=</span><span class="dv">3</span>)</a>
<a class="sourceLine" id="cb415-11" title="11"><span class="kw">lines</span>(<span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">2</span>),mu.free<span class="op">+</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">2</span>)<span class="op">*</span>(mu.P[ind]<span class="op">-</span>mu.free)<span class="op">/</span>sigma.P[ind],<span class="dt">lwd=</span><span class="dv">4</span>,<span class="dt">lty=</span><span class="dv">1</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb415-12" title="12"><span class="co">## show line of optimal portfolios</span></a>
<a class="sourceLine" id="cb415-13" title="13"><span class="kw">points</span>(sigma.P[ind],mu.P[ind],<span class="dt">cex=</span><span class="dv">4</span>,<span class="dt">pch=</span><span class="st">&quot;*&quot;</span>) <span class="co">## show tangency portfolio</span></a>
<a class="sourceLine" id="cb415-14" title="14">ind2 =<span class="st"> </span>(sigma.P <span class="op">==</span><span class="st"> </span><span class="kw">min</span>(sigma.P)) <span class="co">## find the minimum variance portfolio</span></a>
<a class="sourceLine" id="cb415-15" title="15"><span class="kw">points</span>(sigma.P[ind2],mu.P[ind2],<span class="dt">cex=</span><span class="fl">1.5</span>,<span class="dt">pch=</span><span class="st">&quot;+&quot;</span>) <span class="co">## show min var portfolio</span></a>
<a class="sourceLine" id="cb415-16" title="16">ind3 =<span class="st"> </span>(mu.P <span class="op">&gt;</span><span class="st"> </span>mu.P[ind2])</a>
<a class="sourceLine" id="cb415-17" title="17"><span class="kw">lines</span>(sigma.P[ind3],mu.P[ind3],<span class="dt">type=</span><span class="st">&quot;l&quot;</span>,<span class="dt">xlim=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="kw">max</span>(sd.R)<span class="op">*</span><span class="fl">1.1</span>),<span class="dt">ylim=</span><span class="kw">c</span>(<span class="kw">min</span>(mean.R)<span class="op">*</span><span class="fl">1.05</span>, <span class="kw">max</span>(mean.R)<span class="op">*</span><span class="fl">1.1</span>),<span class="dt">lwd=</span><span class="dv">3</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)  <span class="co">##  plot the efficient frontier</span></a>
<a class="sourceLine" id="cb415-18" title="18"><span class="kw">text</span>(sd.R[<span class="dv">1</span>],mean.R[<span class="dv">1</span>],<span class="st">&quot;EUR.USD&quot;</span>,<span class="dt">cex=</span><span class="fl">1.15</span>)</a>
<a class="sourceLine" id="cb415-19" title="19"><span class="kw">text</span>(sd.R[<span class="dv">2</span>],mean.R[<span class="dv">2</span>],<span class="st">&quot;GBP.USD&quot;</span>,<span class="dt">cex=</span><span class="fl">1.15</span>)</a>
<a class="sourceLine" id="cb415-20" title="20"><span class="kw">text</span>(sd.R[<span class="dv">3</span>],mean.R[<span class="dv">3</span>],<span class="st">&quot;OIL.Brent&quot;</span>,<span class="dt">cex=</span><span class="fl">1.15</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-209-1.png" width="672" /></p>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb416-1" title="1">Amat</a></code></pre></div>
<pre><code>##               mean.R      
## EUR.USD   1  0.00154 1 0 0
## GBP.USD   1 -0.00228 0 1 0
## OIL.Brent 1  0.01077 0 0 1</code></pre>
<div class="sourceCode" id="cb418"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb418-1" title="1">bvec</a></code></pre></div>
<pre><code>## [1] 1.0000 0.0107 0.0000 0.0000 0.0000</code></pre>
<p>Here</p>
<ol style="list-style-type: decimal">
<li><code>bvec</code> changes for each of the three assets. Here we see one of them.</li>
<li>The short position <code>bvec</code> has three zeros appended to it.</li>
<li>The <code>Amat</code> constraint matrix has the identity matrix appended to it to represent <span class="math inline">\(w_i = 0\)</span> in the formulation of the inequality constraints parsed by <code>quantprog</code>.</li>
<li>The tangency of the line from the risk-free rate to the maximum Sharpe ratio point on the efficient frontier does not change.</li>
</ol>
<p>The weights are</p>
<pre><code>## [1] 0.0108 0.0000 0.9892</code></pre>
<p>The picture radically changes:</p>
<ol style="list-style-type: decimal">
<li>Long working capital position with only a $1 million euro exposure.</li>
<li>No pounding sterling exposure at all.</li>
<li>A huge $99 million Brent exposure.</li>
</ol>
</div>
</div>
<div id="summary-4" class="section level2">
<h2><span class="header-section-number">6.5</span> Summary</h2>
<p>We learned portfolio maths and finance: building feasible combinations of risk and return called the efficient frontier, figured out in 1952 by Harry Markowitz. We also looked at a simple example of tolerance for loss to imply the amount of collateral (risk-free asset) to hold. Using that idea and a ruler we drew a line to the efficient frontier to discover the best portfolio of exposures for a hypothetical working capital position: the one that maximizes the return for the risk, the ratio that William Sharpe figured out in 1966.</p>
</div>
<div id="further-reading-4" class="section level2">
<h2><span class="header-section-number">6.6</span> Further Reading</h2>
<p>McNeil et al. has sections on . Ruppert et al. has a chapter on portfolio selection upon which much of the <code>R</code> programming in this chapter is based. Bassett et al. has a way forward for more risk management minded analytics that uses quantile regression techniques.</p>
</div>
<div id="practice-laboratory-3" class="section level2">
<h2><span class="header-section-number">6.7</span> Practice Laboratory</h2>
<div id="practice-laboratory-1-1" class="section level3">
<h3><span class="header-section-number">6.7.1</span> Practice laboratory #1</h3>
<div id="problem-6" class="section level4">
<h4><span class="header-section-number">6.7.1.1</span> Problem</h4>
</div>
<div id="questions-6" class="section level4">
<h4><span class="header-section-number">6.7.1.2</span> Questions</h4>
</div>
</div>
<div id="practice-laboratory-2-1" class="section level3">
<h3><span class="header-section-number">6.7.2</span> Practice laboratory #2</h3>
<div id="problem-7" class="section level4">
<h4><span class="header-section-number">6.7.2.1</span> Problem</h4>
</div>
<div id="questions-7" class="section level4">
<h4><span class="header-section-number">6.7.2.2</span> Questions</h4>
</div>
</div>
</div>
<div id="project-2" class="section level2">
<h2><span class="header-section-number">6.8</span> Project</h2>
<div id="background-2" class="section level3">
<h3><span class="header-section-number">6.8.1</span> Background</h3>
</div>
<div id="data-2" class="section level3">
<h3><span class="header-section-number">6.8.2</span> Data</h3>
</div>
<div id="workflow-2" class="section level3">
<h3><span class="header-section-number">6.8.3</span> Workflow</h3>
</div>
<div id="assessment-1" class="section level3">
<h3><span class="header-section-number">6.8.4</span> Assessment</h3>
<p>We will use the following rubric to assess our performance in producing analytic work product for the decision maker.</p>
<ul>
<li><p> The text is laid out cleanly, with clear divisions and transitions
between sections and sub-sections. The writing itself is well-organized, free
of grammatical and other mechanical errors, divided into complete sentences,
logically grouped into paragraphs and sections, and easy to follow from the
presumed level of knowledge.</p></li>
<li><p> All numerical results or summaries are reported to suitable precision,
and with appropriate measures of uncertainty attached when applicable.</p></li>
<li><p> All figures and tables shown are relevant to the argument for
ultimate conclusions. Figures and tables are easy to read, with informative
captions, titles, axis labels and legends, and are placed near the relevant pieces of text.</p></li>
<li><p> The code is formatted and organized so that it is easy for others to
read and understand. It is indented, commented, and uses meaningful names. It
only includes computations which are actually needed to answer the analytical
questions, and avoids redundancy. Code borrowed from the notes, from books,
or from resources found online is explicitly acknowledged and sourced in the
comments. Functions or procedures not directly taken from the notes have
accompanying tests which check whether the code does what it is supposed to.
All code runs, and the <code>R Markdown</code> file <code>knits</code> to <code>pdf_document</code> output, or other output agreed with the instructor.</p></li>
<li><p> Model specifications are described clearly and in appropriate
detail. There are clear explanations of how estimating the model helps to answer
the analytical questions, and rationales for all modeling choices. If multiple
models are compared, they are all clearly described, along with the rationale
for considering multiple models, and the reasons for selecting one model over
another, or for using multiple models simultaneously.</p></li>
<li><p> The actual estimation and simulation of model parameters or estimated functions is technically correct. All calculations based on estimates are clearly explained, and also technically correct. All estimates or derived quantities are
accompanied with appropriate measures of uncertainty.</p></li>
<li><p> The substantive, analytical questions are all answered as
precisely as the data and the model allow. The chain of reasoning from estimation
results about the model, or derived quantities, to substantive conclusions
is both clear and convincing. Contingent answers (for example, “if X, then Y , but if A, then B, else C”) are likewise described as warranted by the model and data. If uncertainties in the data and model mean the answers to some questions must be imprecise, this too is reflected in the conclusions.</p></li>
<li><p> All sources used, whether in conversation, print, online, or otherwise are listed and acknowledged where they used in code, words, pictures, and any other components of the analysis.</p></li>
</ul>
</div>
</div>
<div id="references-2" class="section level2">
<h2><span class="header-section-number">6.9</span> References</h2>
<p>Bassett, Gilbert W., Jr., Roger Koenker, and Gregory Kordas. 2004. Pessimistic Portfolio Allocation and Choquet Expected Utility. Journal of Financial Econometrics (2004) 2 (4): 477-492.</p>
<p>Markowitz, Harry. 1952. Portfolio Selection. The Journal of Finance, Vol. 7, No. 1. (March, 1952), pp. 77-91.</p>
<p>McNeill, Alexander J., Rudiger Frey, and Paul Embrechts. 2015. Quantitative Risk Management: Concepts, Techniques and Tools. Revised Edition. Princeton: Princeton University Press.</p>
<p>Ruppert, David and David S. Matteson. 2015. Statistics and Data Analysis for Financial Engineering with R Examples, Second Edition. New York: Springer.</p>
<p>Sharpe, William F. 1966. “Mutual Fund Performance.” Journal of Business, January 1966, pp. 119-138.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="market-risk.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="aggregating-enterprise-risk.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/09-portfolioanalytics.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
